f = open('admin.html', 'r', encoding='utf-8')
lines = f.readlines()
f.close()
lines[1033] = lines[1033].replace('supendido', 'suspendido')
lines[1033] = lines[1033].replace('etado_pago', 'estado_pago')
lines[1033] = lines[1033].replace('<pan ', '<span ')
f = open('admin.html', 'w', encoding='utf-8')
f.writelines(lines)
f.close()
print(lines[1033].strip()[:200])
